### ISSUE TITLE
Should we require multiple issuers per redeemer?

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/privacy-proxy#13]
We don't want to encourage cases where a specific issuer can block a mediator wholesale, such as one company preferring you to use its mediator instead of another mediator. To mitigate against this, we could require that there are always multiple issuers supported by a redeemer.

The complexity this raises is that the issuers would have different state held for rate limiting.

**Comment by dvorak42** [comment]
It seems like with multiple issuers for the same origin, the mediator will need to be bound to a single issuer or keeping its own state about what issuers a certain client has talked to, otherwise clients could easily multiply the tokens they are supposed to get under a single origin policy by all the available issuers the origin/redeemer supports. Cross-company cross-issuer rate limiting seems like it would require a lot of consistency infrastructure to avoid having a decent gap when clients could effectively double-issue tokens.

**Comment by tfpauly** [comment]
Agreed. The other approach here would be to detect/prevent Issuers from blocking specific Mediators just because they want to prefer a Mediator that they have more control over or can collude with.
