### ISSUE TITLE
Add rationale for anon origin ID

### ISSUE THREAD

**Issue by tfpauly** [tfpauly/privacy-proxy#142]
The anon origin ID allows attesters to track the buckets as seen from the client. Without this, rotations on the issuer for the index generation would cause the counts to reset (in the middle of a window for some client). Having consistent counts relies on the client communicating information to the attester.

**Comment by chris-wood** [comment]
Here's a sketch describing the interaction between origin secrets and anon origin IDs. We could start with a simplified version of the protocol that has no origin secret rotation, which would not require anon origin ID to ensure stability. Then we can say that since these are rotated, causing client state to be reset, we need something to maintain the mapping across rotation windows, and that's the anon origin ID. 

~~~
                     (rotate)        (rotate)  
Issuer:      -----+-----|---------+-----|------
                  | policy window | ...
Client:           |---------------|
               (start)          (end)
~~~

**Comment by tfpauly** [comment]
I think this is better explained in current versions

**Comment by tfpauly** [comment]
@chris-wood can we close this now? Or do we still want more pictures?

**Comment by chris-wood** [comment]
I'll address this as followup to #213.
