### ISSUE TITLE
Binding between ORIGIN_ID and token request

### ISSUE THREAD

**Issue by chris-wood** [tfpauly/privacy-proxy#51]
Clients can currently request tokens for A.com but lie -- in the origin header -- that it's a request for B.com. If issuer keys are not per-origin, then clients can abuse this to get more tokens than allowed by policy. If issuer keys are per-origin, then the mediator can learn the origin since it sees the key ID. I think one of these has to give. 

It's probably fine to hide the key ID from the mediator. The reason it's exposed now is so the mediator can check for consistency and ensure the client isn't targeted, though I don't see how this check solves that problem. (I've also forgotten why this is important, since there are other ways for origins to link client activity if they're malicious, e.g., A.com can just tell B.com that the client visited.)

**Comment by tfpauly** [comment]
The key ID needs to be validated by the mediator to ensure that the client doesn't have a unique key, for targeting. I don't think a.com would be able to leak information to b.com otherwise.

I don't understand the problem you're describing here about how a client could lie.

Let's say I'm talking to a.com. I've resolved DNS for a.com, I'm talking to it's address, and I have a TLS session with a.com. a.com knows that it is a.com on this server, and not b.com, because of the TLS handshake and SNI.

When I issue an HTTP request, I'll include the `:authority` pseudo-header (in H2) which will indicate a.com, because if I put in b.com, it will fail. The origin will then send a TokenChallenge where the origin_name is set to a.com.

I don't think setting an Origin HTTP header matters at all—that just says what the parent page is. There's no reason that the server should serve up TokenChallenges based on the Origin header, and not the actual Host/authority. Maybe we just need to have a sentence clarifying that?

**Comment by chris-wood** [comment]
> I don't understand the problem you're describing here about how a client could lie.

I think you're assuming an honest client? It's pretty trivial for the client to connect to a.com, get a challenge for a.com, but then tell the issuer that its origin is actually b.com. RIght?

**Comment by tfpauly** [comment]
Ah, I see your point now. I'm wondering if we should then:

- Use per-origin keys
- Remove the cleartext key_id from the AccessTokenRequest
- Move away from Token-Origin as a header, to being an encrypted origin_name in the AccessTokenRequest
- Perhaps also include an encrypted key_id along with the encrypted origin_name in the AccessTokenRequest

This would then have the consequence of not letting the mediator help validate that there aren't per-client keys, though.

**Comment by tfpauly** [comment]
I wonder if the targeting thing is partly solved by *not* sending the token key_id in the request, and relying on the origin name being decrypted. Because then the issuer wouldn’t know which key to use other than the default/only per-origin key, otherwise the validation would fail.
